##
# Default server configuration
#server {
#	listen 80 default_server;
#	listen [::]:80 default_server;
#	root /var/www/html;
#	index index.html index.htm index.nginx-debian.html;
#
#	server_name _;
#
#	location / {
#		try_files $uri $uri/ =404;
#	}
#
#}

server {
        listen 80;
        server_name test.foo.bar;
        location / {
                add_header Content-Type text/plain;
                return 200 'Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nginx is already the newest version (1.24.0-2ubuntu7.5).
The following packages were automatically installed and are no longer required:
  alsa-topology-conf alsa-ucm-conf ca-certificates-java fontconfig-config fonts-dejavu-core fonts-dejavu-mono java-common
  libasound2-data libasound2t64 libavahi-client3 libavahi-common-data libavahi-common3 libcups2t64 libfontconfig1 libgraphite2-3
  libharfbuzz0b libjpeg-turbo8 libjpeg8 liblcms2-2 libpcsclite1 openjdk-11-jre-headless
Use apt autoremove to remove them.
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
\n';
        }
}


server {
        listen 80;
        server_name test.fosi.nfo;
        location / {
                add_header Content-Type application/xml;
                return 200 '<widget>
    <debug>on</debug>
    <window title="Sample Konfabulator Widget">
        <name>main_window</name>
        <width>500</width>
        <height>500</height>
    </window>
    <image src="Images/Sun.png" name="sun1">
        <hOffset>250</hOffset>
        <vOffset>250</vOffset>
        <alignment>center</alignment>
    </image>
    <text data="Click Here" size="36" style="bold">
        <name>text1</name>
        <hOffset>250</hOffset>
        <vOffset>100</vOffset>
        <alignment>center</alignment>
        <onMouseUp>
            sun1.opacity = (sun1.opacity / 100) * 90;
        </onMouseUp>
    </text>
</widget>\n';
        }
}


server {
        listen 80;
        server_name test.yoop.jpo;
        location / {
                add_header Content-Type application/json;
                return 200 '{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}\n';
        }
}

